__author__ = 'max'

import re

MAX_CHAR_LENGTH = 45

# Regular expressions used to normalize digits.
DIGIT_RE = re.compile(r"\d")

PAD = "_PAD"
PAD_POS = "_PAD_POS"
PAD_UPOS = "_PAD_UPOS"
PAD_XPOS = "_PAD_XPOS"
PAD_TYPE = "_<PAD>"
PAD_CHAR = "_PAD_CHAR"
PAD_CHUNK = "_PAD_CHUNK"
PAD_NER = "_PAD_NER"

ROOT = "_ROOT"
ROOT_LEMMA = "_ROOT_LEMMA"
ROOT_POS = "_ROOT_POS"
ROOT_UPOS = "_ROOT_UPOS"
ROOT_XPOS = "_ROOT_XPOS"
ROOT_FEATS = "_ROOT_FEATS"
ROOT_TYPE = "_<ROOT>"
ROOT_CHAR = "_ROOT_CHAR"
ROOT_DEPS = "_ROOT_DEPS"
ROOT_MISC = "_ROOT_MISC"

END = "_END"
END_LEMMA = "_END_LEMMA"
END_POS = "_END_POS"
END_UPOS = "_END_UPOS"
END_XPOS = "_END_XPOS"
END_FEATS = "_END_FEATS"
END_TYPE = "_<END>"
END_CHAR = "_END_CHAR"
END_DEPS = "_END_DEPS"
END_MISC = "_END_MISC"

UNK_ID = 0
PAD_ID_WORD = 1
PAD_ID_CHAR = 1
PAD_ID_TAG = 0
